# Generated by Django 3.1.1 on 2020-09-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200909_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_md',
        ),
    ]
